language: node_js
node_js: node
dist: trusty
apt:
  packages:
    - chromium-browser
before_install: # https://docs.travis-ci.com/user/gui-and-headless-browsers
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script: npm install -g angular-cli karma
script:
- ng lint # run linting
- ng test --single-run # run unit tests
- ng serve & export NG_SERVE_PID=$! ; ng e2e # run server, then execute end-to-end tests
after_script:
- kill $NG_SERVE_PID
- unset NG_SERVE_PID
deploy:
  provider: script
  script: ng github-pages:deploy
  on:
    branch: master
