language: node_js
node_js: node
dist: trusty
apt:
  packages:
  - chromium-browser
before_install:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script: npm install -g angular-cli karma
script:
- ng lint
- ng test --single-run
- ng serve & export NG_SERVE_PID=$! ; ng e2e
after_script:
- kill $NG_SERVE_PID
- unset NG_SERVE_PID
after_success:
  - |
       $(npm bin)/set-up-ssh --key "$encrypted_2265753103d1_key" \
                             --iv "$encrypted_2265753103d1_iv" \
                             --path-encrypted-key ".travis/github_deploy_key.enc"
deploy:
  skip_cleanup: true
  provider: script
  script: ng github-pages:deploy
  on:
    branch: master
